import { useEffect, useState } from 'react';
import { apiUrl, supabase } from './supabase';

const questions = [
  ['What do we call learners at BRIGHTCODERS?', ['Little Heroes', 'Super Teachers', 'Bright Stars'], 0],
  ['Which value means asking questions and exploring?', ['Kindness', 'Curiosity', 'Courage'], 1],
  ['What is our school motto?', ['Learn today, lead tomorrow', 'For future, for better', 'Dream big always'], 1]
];

function Header({ user, role, onLogout }) {
  return <header><nav className="nav container"><a className="logo" href="#/">BRIGHT<span>CODERS</span><small>ACADEMY</small></a><div className="links"><a href="#/">Home</a><a href="#/apply">Admissions</a>{user ? <><a href={role === 'admin' ? '#/admin' : '#/account'}>{role === 'admin' ? 'Admin' : 'My account'}</a><button onClick={onLogout}>Log out</button></> : <a href="#/login">Login</a>}</div></nav></header>;
}

function Home() { const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(''); const q = questions[index]; return <>
  <section className="hero"><div className="container"><p className="tag">Welcome to BRIGHTCODERS ACADEMY</p><h1>Little <em>Heroes</em>,<br />big bright futures.</h1><p className="motto">“For future, for better.”</p><p>Where young minds explore, create, and grow with confidence every day.</p><a className="button" href="#/apply">Start your journey</a></div></section>
  <section className="container section two"><div><p className="tag dark">Our story</p><h2>Built for curious minds</h2></div><p>BRIGHTCODERS ACADEMY gives every child a joyful place to learn, imagine, and belong. Our little heroes bring energy and ideas to every classroom and school project.</p></section>
  <section className="cream"><div className="container section"><p className="tag dark">What guides us</p><h2>Our values</h2><div className="cards">{[['♥','Kindness','We care for ourselves, one another, and our community.'],['✦','Curiosity','We ask questions, discover new ideas, and love learning.'],['↗','Courage','We try our best, learn from mistakes, and keep growing.']].map(v=><article className="card" key={v[1]}><div className="icon">{v[0]}</div><h3>{v[1]}</h3><p>{v[2]}</p></article>)}</div></div></section>
  <section className="blue"><div className="container section two"><div><p className="tag">Hero challenge</p><h2>Can you answer the bright question?</h2><p>Play a quick school-themed quiz while you visit.</p></div><div className="game"><p>{q[0]}</p>{q[1].map((a,i)=><button className="answer" key={a} onClick={()=>setAnswer(i===q[2]?'Correct — you are a bright hero!':'Nice try! Choose a new question and keep learning.')}>{a}</button>)}<p>{answer}</p><button className="button" onClick={()=>{setIndex((index+1)%questions.length);setAnswer('')}}>New question</button></div></div></section>
 </> }

function Apply() { const [notice,setNotice] = useState(''); async function submit(e) { e.preventDefault(); setNotice('Sending your enquiry…'); const form = new FormData(e.currentTarget); const res = await fetch(`${apiUrl}/api/applications`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parent_name:form.get('name'),email:form.get('email'),learner_age:Number(form.get('age'))})}); if(res.ok){e.currentTarget.reset();setNotice('Thank you! We will be in touch soon.')}else setNotice('We could not send your enquiry. Please try again.'); } return <main className="container section"><p className="tag dark">Admissions</p><h1>Become a Brightcoder</h1><form onSubmit={submit}><label>Parent/Guardian name<input name="name" required /></label><label>Email address<input name="email" type="email" required /></label><label>Learner's age<input name="age" type="number" min="2" max="18" required /></label><button className="button">Send enquiry</button><p>{notice}</p></form></main> }

function Login({setRoute}) { const [notice,setNotice] = useState(''); async function login(e){e.preventDefault(); const data=new FormData(e.currentTarget); const {error}=await supabase.auth.signInWithPassword({email:data.get('email'),password:data.get('password')}); if(error)setNotice(error.message);else setRoute('#/account');} async function signup(e){const data=new FormData(e.currentTarget);const {error}=await supabase.auth.signUp({email:data.get('email'),password:data.get('password')});setNotice(error?error.message:'Account created. Check your email to confirm it.');} return <main className="container section"><div className="auth"><p className="tag dark">Parent & staff portal</p><h1>Welcome back</h1><form onSubmit={login}><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" required /></label><button className="button">Log in</button><button type="button" className="link-button" onClick={signup}>Create an account</button><p>{notice}</p></form></div></main> }

const adminResources={applications:{title:'Admissions',fields:[['parent_name','Parent name'],['email','Email','email'],['learner_age','Learner age','number'],['phone','Phone'],['grade_interest','Grade interest'],['status','Status']]},grades:{title:'Grades',fields:[['name','Grade name'],['description','Description']]},streams:{title:'Streams',fields:[['name','Stream name'],['grade_id','Grade ID','number']]},staff:{title:'Staff',fields:[['first_name','First name'],['last_name','Last name'],['email','Email','email'],['phone','Phone'],['role','Role'],['grade_id','Grade ID','number'],['stream_id','Stream ID','number']]},students:{title:'Students',fields:[['admission_no','Admission number'],['first_name','First name'],['last_name','Last name'],['grade_id','Grade ID','number'],['stream_id','Stream ID','number'],['guardian_name','Guardian'],['guardian_phone','Guardian phone']]},fees:{title:'Fees',fields:[['student_id','Student ID','number'],['amount','Amount','number'],['term','Term'],['academic_year','Academic year','number'],['method','Payment method'],['reference','Receipt/reference'],['paid_on','Payment date','date']]}};
function Admin({session,role}){const [resource,setResource]=useState('applications'),[items,setItems]=useState(null),[summary,setSummary]=useState({}),[notice,setNotice]=useState('');const token=session?.access_token;const load=async()=>{try{const h={Authorization:`Bearer ${token}`};const [a,b]=await Promise.all([fetch(`${apiUrl}/api/admin/${resource}`,{headers:h}),fetch(`${apiUrl}/api/admin/summary`,{headers:h})]);if(!a.ok||!b.ok)throw Error();setItems(await a.json());setSummary(await b.json())}catch{setItems(false)}};useEffect(()=>{if(role==='admin'&&token)load()},[resource,role,token]);const add=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));Object.keys(data).forEach(k=>{if(data[k]==='')delete data[k]});const r=await fetch(`${apiUrl}/api/admin/${resource}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(data)});setNotice(r.ok?'Saved successfully.':'Could not save record.');if(r.ok){e.currentTarget.reset();load()}};if(role!=='admin')return <main className="container section"><h1>Admin access required</h1></main>;const c=adminResources[resource];return <main className="container section"><p className="tag dark">School management</p><h1>Admin dashboard</h1><div className="admin-tabs">{Object.entries(adminResources).map(([k,v])=><button className={resource===k?'active':''} onClick={()=>setResource(k)} key={k}>{v.title} ({summary[k]??0})</button>)}</div><section className="admin-grid"><div><h2>{c.title}</h2>{items===null?<p>Loading…</p>:items===false?<p>Could not load records.</p>:items.length?items.map(x=><article className="card" key={x.id}><strong>{x.parent_name||x.name||`${x.first_name||''} ${x.last_name||''}`}</strong><p>{Object.entries(x).filter(([k])=>!['id','created_at','parent_name','name','first_name','last_name'].includes(k)).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v}`).join(' · ')}</p></article>):<p>No records yet.</p>}</div><div className="auth"><h2>Add record</h2><form onSubmit={add}>{c.fields.map(([n,l,t])=><label key={n}>{l}<input name={n} type={t||'text'} required={!['phone','description','reference','grade_id','stream_id'].includes(n)}/></label>)}<button className="button">Save</button><p>{notice}</p></form></div></section></main>}

export default function App(){
  const [route,setRouteState]=useState(location.hash||'#/'); const [session,setSession]=useState(null); const [role,setRole]=useState(null);
  const user=session?.user; const setRoute=x=>{location.hash=x;setRouteState(x)};
  useEffect(()=>{const sync=()=>setRouteState(location.hash||'#/');addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);
  useEffect(()=>{ const load=async s=>{setSession(s); if(s?.user){const {data:p}=await supabase.from('profiles').select('role').eq('id',s.user.id).single();setRole(p?.role||'parent')}else setRole(null)}; supabase.auth.getSession().then(({data})=>load(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>load(s));return()=>subscription.unsubscribe()},[]);
  const logout=async()=>{await supabase.auth.signOut();setRoute('#/')};
  const page=route==='#/apply'?<Apply/>:route==='#/login'?<Login setRoute={setRoute}/>:route==='#/admin'?<Admin session={session} role={role}/>:route==='#/account'?<main className="container section"><h1>My account</h1><p>{user?`Signed in as ${user.email}.`:'Please log in.'}</p></main>:<Home/>;
  return <><Header user={user} role={role} onLogout={logout}/>{page}<footer>BRIGHTCODERS ACADEMY · Little minds, big dreams</footer></>;
}
